### ISSUE TITLE
Will the released data contain the diagnose reports?

### ISSUE THREAD

**Issue by muziyongshixin** [MIT-LCP/mimic-cxr#1]
I have a great interest in this dataset, and I have read the dataset paper (https://arxiv.org/pdf/1901.07042.pdf), I am wondering whether the original reports will be released at the same time?

**Comment by alistairewj** [comment]
We plan to publish the DICOMs with the reports very soon, hopefully in the
next few months. There will be a paper focused on the data as well.

**Comment by aldraus** [comment]
Dear Alistair,

Do you still plan to publish the DICOMs? If so, when?

Thanks

**Comment by alistairewj** [comment]
The DICOMs are now published along with the free-text radiology reports. See the PhysioNet page: https://physionet.org/content/mimic-cxr/2.0.0/
