### ISSUE TITLE
validation set for chexpert and negbio comparison

### ISSUE THREAD

**Issue by xiaosongwang** [MIT-LCP/mimic-cxr#10]
Hi, 

where can I access the "/db/rr-labeled/mimic_cxr_labeled_mpl.csv" or "mimic_cxr_validation_reports.csv" files? It will be really helpful for a  comparison study if I can have them. Many thanks!

**Comment by alistairewj** [comment]
This set is not public as of now.

**Comment by xiaosongwang** [comment]
Thank you for the quick reply. Any plan to publish it?

**Comment by alistairewj** [comment]
Not at the moment, sorry!
