### ISSUE TITLE
temporal ordering and clinical data

### ISSUE THREAD

**Issue by KerollosWanis** [MIT-LCP/mimic-cxr#11]
Hi,

Is there any way to know, given a particular patient, when the chest x-rays were taken relative to one another? And is there any way to link the images to clinical data for a given patient?

Thank you

**Comment by alistairewj** [comment]
You can use the `StudyDate` in the DICOM header for this information. Eventually I plan on adding in a derived meta-data spreadsheet which gives the info in a form that's easier to query.

**Comment by KerollosWanis** [comment]
Thank you! There is no associated clinical data for any of the subject ids currently, correct?

**Comment by alistairewj** [comment]
Not currently but stay tuned!
