### ISSUE TITLE
Summary statistics for MIMIC CXR dataset

### ISSUE THREAD

**Issue by jarrelscy** [MIT-LCP/mimic-cxr#12]
Hi authors,
 
Just wanted to clarify some questions about MIMIC CXR:
 
1. Were there any inclusion / exclusion criteria for the dataset? 
From the Nature Scientific Data paper it appears that it was simply all available chest x-rays taken between 2011 and 2016, with some age cutoff.  

2. Are there some summary statistics for the dataset available?
a. Mean, min, max of participant age
b. Male / female percentage
c. Inpatient vs Outpatient vs ED
d. Ethnicity percentages 
e. Manufacturer / model of devices 

3. Were any of the images taken at satellite locations or were they only from Beth Israel Deaconess Medical Center? 
 

Thanks,
Jarrel

**Comment by alistairewj** [comment]
Hello!

> Were there any inclusion / exclusion criteria for the dataset?
From the Nature Scientific Data paper it appears that it was simply all available chest x-rays taken between 2011 and 2016, with some age cutoff.

The inclusion criteria were adult patients with an admission to the BIDMC ED between 2011 - 2016.

> Are there some summary statistics for the dataset available?
a. Mean, min, max of participant age
b. Male / female percentage
c. Inpatient vs Outpatient vs ED
d. Ethnicity percentages
e. Manufacturer / model of devices

No demographic information is available for MIMIC-CXR but in the future it will be linkable to clinical data. We won't release any manufacturer data though.

> Were any of the images taken at satellite locations or were they only from Beth Israel Deaconess Medical Center?

All of them were reviewed by a radiologist at the BIDMC, but sometimes (very rarely) you get referral clinic x-rays reviewed by BIDMC radiologists.

**Comment by jarrelscy** [comment]
Hi Alistair!

Thanks for the reply! Just to clarify, does adult in this setting mean 18
years and above?

Regards,
Jarrel

**Comment by alistairewj** [comment]
Yes in Massachusetts adults at >= 18.
