### ISSUE TITLE
The number of frontal and lateral chest radiographs

### ISSUE THREAD

**Issue by fzfs** [MIT-LCP/mimic-cxr#15]
Hi authors,

Paper MIMIC-CXR-JPG, A LARGE PUBLICLY AVAILABLE DATABASE OF LABELED CHEST RADIOGRAPHS listed  the number of frontal and lateral chest radiographs in the three datasets. However in the file mimic-cxr-2.0.0-metadata.csv, there were 15769 null values (missing) in column ViewPosition. So were there any non-manual methods to determine which view for these samples?

Many thanks!

**Comment by alistairewj** [comment]
There are sometimes other DICOM fields which will give an idea of what the view position is. Have you tried ViewCodeSequence `0x00540220`?

**Comment by fzfs** [comment]
Thank you! Actually in the file mimic-cxr-2.0.0-metadata.csv, when there was null value (missing) in column ViewPosition，the value in column ViewCodeSequence was still null.

**Comment by alistairewj** [comment]
Hmm, thinking back that makes sense. I did a lot of harmonizing of distinct DICOM fields to get the missing data down to ~15769 / 370,000, so I've probably already scoured similar fields and imputed view code with them. The last alternative would be to use the procedure code, and if it only mentions PA/AP, then it's a frontal x-ray. Beyond that, training a model to classify the image is the best bet. Probably not too crazy to do! I also noted sometimes the view position is wrong (but it's very rare, like 0.1% or so) - so the classifier could be used to correct those as well.

**Comment by fzfs** [comment]
I see, thank you for the reply.
