### ISSUE TITLE
MIMIC-CXR data on PhysioNet only contains a LICENSE.txt file

### ISSUE THREAD

**Issue by anantzoid** [MIT-LCP/mimic-cxr#2]
Hi authors,

I credentialed my account on Physionet was was given access to the [MIMIC-CXR](https://alpha.physionet.org/content/mimic-cxr/1.0.0/) dataset. But it looks like the only data it contains is a LICENSE.txt file.
Do you plan to upload the data anytime soon? Or should I be looking somewhere else?

Thanks,
Anant

**Comment by alistairewj** [comment]
Indeed this is not intended! At the moment the new PhysioNet platform doesn't behave well with 200,000+ files in a single listing, so we are working out a way to make work better. Once we do we will upload thew new set. We also intend to update the organization of the files so stay tuned for that (it will be referred to as v1.1.0).

**Comment by anantzoid** [comment]
@alistairewj  Thanks for the update. Is there any way I can have access to MIMIC-CXR at the moment? If not, do you have an idea of when the first copy of the data should be available?

**Comment by alistairewj** [comment]
The data is now available as DICOM formatted images with free-text radiology reports. See the PhysioNet page: https://physionet.org/content/mimic-cxr/2.0.0/
