### ISSUE TITLE
How can i get the mimic datasets? 

### ISSUE THREAD

**Issue by dxs66** [MIT-LCP/mimic-cxr#20]
When i register the CITI account to get the access the course for a credentialed PhysioNet account, they ask me for the Massachusetts Institute of Technology Affiliates's email? I can not get these. Can you help me for getting the datasets of mimic-cxr? Thank you！

**Comment by alistairewj** [comment]
I believe the statement is along the lines of "*if* you have an MIT e-mail...". If you don't have an MIT e-mail, just use the same e-mail you used for your PhysioNet account.

**Comment by dxs66** [comment]
Thank you, I get it.
