### ISSUE TITLE
Is there a way to link the MIMIC-CXR and MIMIC-III datasets?

### ISSUE THREAD

**Issue by tbj128** [MIT-LCP/mimic-cxr#3]
I'm new to the MIMIC datasets. I was wondering the two datasets intrinsically linked? If yes, is there or will there be an common identifier between the two datasets?

**Comment by alistairewj** [comment]
There is no way to link MIMIC-III and MIMIC-CXR.

We plan to allow linking MIMIC-CXR with MIMIC-IV. The `subject_id` will be the common identifier.
