### ISSUE TITLE
Metadata recording your modifications to the DICOM files

### ISSUE THREAD

**Issue by howff** [MIT-LCP/mimic-cxr#6]
Where have you recorded the metadata which describes the modifications you have made to the DICOM files?
For example when you blank out a section of the image due to it containing possible PII where do you  record the region which you modified?

**Comment by alistairewj** [comment]
A paper with more detail about the dataset generation will be out soon!

The black box is annotated as a graphic object, i.e. the Graphic Object Sequence (0070, 0009) under the Graphic Annotation Sequence (0070, 0001) data element was used to store coordinates of the obscuring black boxes used to clean the pixel data.

**Comment by alistairewj** [comment]
Paper is out with these details! https://www.nature.com/articles/s41597-019-0322-0
