### ISSUE TITLE
What is the total disk space required to download the dataset

### ISSUE THREAD

**Issue by munachisonwadike** [MIT-LCP/mimic-cxr#8]
It is unclear from the website and Physionet paper, what the exact size of the files in MIMIC-CXR-JPG is. I would greatly appreciate the help in understanding this space requirement?

**Comment by alistairewj** [comment]
Yeah unfortunately PhysioNet isn't displaying the dataset sizes correctly for MIMIC-CXR and MIMIC-CXR-JPG. The DICOM dataset is 4.7 TB and the JPG dataset is something like 500 - 600 GB.

**Comment by alistairewj** [comment]
We updated the dataset size on the PhysioNet page so this should be clearer for all users now.
